### ISSUE TITLE
require-multiple-commits value treated as string

### ISSUE THREAD

**Issue by C6H6** [beemojs/conventional-pr-action#24]
```
[...]
  if (getInput('require-multiple-commits') && pr.commits < 2)
[...]
```
`getInput()` returns string so in case the configuration is `require-multiple-commits: false` it will not work properly.
`getBooleanInput()` should be used instead.

**Comment by milesj** [comment]
@C6H6 Thanks for pointing this out. Never seen `getBooleanInput`, so it must be new since I initially built this. Should be an easy fix.
