### ISSUE TITLE
Auto install assumes a package.json in the base folder and breaks if one is not found

### ISSUE THREAD

**Issue by bbugh** [beemojs/conventional-pr-action#25]
As title says, the action expects that a package.json is in the root folder, which is not always the case for monorepos. If a package.json is not found, creating one before running `npm ci` would resolve this issue.

**Comment by milesj** [comment]
@bbugh Oh wow, never even thought about this being used in a non-JS project 😅 

Auto-creating it seems like a viable solution then.
