### ISSUE TITLE
Commits whose titles start with `feat:` are considered invalid

### ISSUE THREAD

**Issue by mykola-mokhnach** [beemojs/conventional-pr-action#30]
Steps to reproduce:
- Add the following action to your repository: https://github.com/appium/appium-uiautomator2-driver/blob/master/.github/workflows/pr-title.yml
- Create a new PR with a title starting with `feat: `
- Check the action output

Actual result:
The validation fails.This does not happen for other valid prefixes, like `ci:` or `docs:`. See https://github.com/appium/appium-uiautomator2-driver/runs/8222140787?check_suite_focus=true

Expected result:
All prefixes defined at https://www.conventionalcommits.org/en/v1.0.0/ must be recognized as valid ones.

**Comment by milesj** [comment]
@mykola-mokhnach This actions defaults to this preset, https://github.com/beemojs/conventional-changelog-beemo, which does not support `feat`. You'd need to configure the action with the `config-preset` option and change it to angular, or whatever preset you'd like.

**Comment by mykola-mokhnach** [comment]
Thanks, I will change the config. Perhaps it would be easier to catch such issues if presets would have more detailed description in the documentation.
