### ISSUE TITLE
commit update still considered invalid

### ISSUE THREAD

**Issue by oc-stephen-bennett** [beemojs/conventional-pr-action#31]
Hi, 

Not sure if this is a user error (aka me) or bug, but if you do:

- PR with a commit message that is not a `conventional commit`
- Action fails due to invalid commit !
- User does a rebase and updates commit message
- git push --force origin branch name
- this updates github and i see the commits show up as coventional commits
- job reruns
- job fails again saying: 
![image](https://user-images.githubusercontent.com/100411569/191787974-1d068a3e-7489-49c6-bee0-dd5cb5fd1d25.png)

**Comment by milesj** [comment]
@oc-stephen-bennett What's the actually title message?

**Comment by oc-stephen-bennett** [comment]
Sorry its a me problem! i updated all the commits, but the PR title didnt match conventional commits.. (it was in the error message even.. ) 

great tool and thanks for the quick reply
