### ISSUE TITLE
Action doesn't actually follow commitlint convention

### ISSUE THREAD

**Issue by ThomasAribart** [beemojs/conventional-pr-action#32]
Hello and thanks for you work !

I found out that action fails when using valid commit types like `feat` and `refactor`. Is it normal ? Am I doing something wrong ?

https://commitlint.js.org/#/

**Comment by milesj** [comment]
@ThomasAribart You need to change the `config-preset` option, it defaults to https://github.com/beemojs/conventional-changelog-beemo

**Comment by milesj** [comment]
@ThomasAribart Nope, because that's the point of presets, they're all different. 

You're probably referring to the Angular preset.
