### ISSUE TITLE
When this action runs it modifies the package.json of any node project present.

### ISSUE THREAD

**Issue by jeacott1** [beemojs/conventional-pr-action#34]
if I create an action and checkout a node/react/whatever project with a package.json file,
when this conventional-pr-action is run the package.json is modified, adding: 
```
  "dependencies": {
  ...
    "conventional-changelog-beemo": "^3.0.1",
    
 ```

this is clearly undesirable.

**Comment by milesj** [comment]
@jeacott1 Set the `auto-install` option to false.

**Comment by jeacott1** [comment]
@milesj with auto-install false the action doesn't work. 
Error: Preset "conventional-changelog-beemo" does not exist.

**Comment by milesj** [comment]
@jeacott1 Yes, that pakage is required and that's why `auto-install` installs it. Either auto-install, install it manually, or change your preset.

**Comment by jeacott1** [comment]
@milesj I dont see any docs on how that should be done, nor how I would expect to do that without affecting my target project? what's the point of a build validation tool that pollutes the build?

**Comment by milesj** [comment]
@jeacott1 Conventional commits requires a preset, which is an npm package. It needs to be installed somehow.

This action auto-installs it to simply the process. Typically the action is ran in isolation (as seen here: https://github.com/beemojs/beemo/blob/master/.github/workflows/pr.yml#L5) which is a non-issue. I'm curious why you think this is undesirable since it happens in CI and is not committed?

**Comment by jeacott1** [comment]
@milesj I'm using this on a react project that has its own package.json. on PR first the PR is vetted by this action for conventional commits - which modifies MY PROJECTs package.json. I then build my project, run tests, and push snapshot artifacts.
the fact that this project alters the dependency list of my project is is clearly a problem - it could affect/break things, add libs and transient dependencies.

for releases it isnt an issue because I dont invoke this action. 

perhaps if there was an option, or it defaulted to running in a different working directory it would fix the issue? or perhaps better, containerise a version so that it's faster to start and wont try to modify things on the host.

**Comment by milesj** [comment]
Well there is an option to disable it:

```yaml
- uses: beemojs/conventional-pr-action@v2
  with:
    auto-install: false
```

I've also updated the readme with some instructions on these approaches.

**Comment by jeacott1** [comment]
why dont you just checkout this action to a different directory? wouldnt that fix this issue?

'If you don't want to use automatic installation, you'll need to disable the auto-install option, and add your chosen preset manually to devDependencies in the root package.json."

isnt the root package json here going to be the working tree of the target projects checkout still? manual or auto - how does this help?

**Comment by jeacott1** [comment]
why would I commit "conventional-changelog-beemo": "^3.0.1" as a dependency of my project - it just isnt.

I'll just find a different action I think.
thanks.

**Comment by milesj** [comment]
@jeacott1 That's how the npm conventional commits packages work.

https://www.npmjs.com/package/conventional-commits-parser

**Comment by jeacott1** [comment]
@milesj sure - so when you setup your action - do it in a different folder and run it from there. (ie use a different working dir). then your npm install will install to your project, and my project will remain untouched.

**Comment by milesj** [comment]
I don't disagree, just letting you know how it currently works.

**Comment by jeacott1** [comment]
@milesj sure - I guess the only workaround then is to run it as a separate job as a pre-workflow.
